### ISSUE TITLE
Incompatible optimizer weight

### ISSUE THREAD

**Issue by Zumbalamambo** [oarriaga/face_classification#18]
Newest commit fires the following error

```
  File "C:/face_classification-master/face_classification-master/src/video_emotion_color_demo.py", line 26, in <module>
    emotion_classifier = load_model(emotion_model_path, custom_objects=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\models.py", line 272, in load_model
    model.optimizer.set_weights(optimizer_weight_values)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\optimizers.py", line 79, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Optimizer weight shape (8,) not compatible with provided weight shape (64,)

```

**Comment by oarriaga** [comment]
Hello,
Which version of keras are you using?
Also did you change the line in the file since the original line should contain the following in line 26

> emotion_classifier = load_model(emotion_model_path, compile=False)

With the compile function set to False

**Comment by Zumbalamambo** [comment]
Im using version 2 of keras. 

Yes :) I changed it to custom_objects since it is firing an error message if i include `compile`.

**Comment by oarriaga** [comment]
Which error line is it firing?

**Comment by Zumbalamambo** [comment]
The following line fires the error message

```
emotion_classifier = load_model(emotion_model_path, compile=False)
gender_classifier = load_model(gender_model_path, compile=False)

```

**Comment by Zumbalamambo** [comment]
It worked now after creating  a new environment. but why is that the accuracy drops for multiple persons? If there are multiple persons within the frame, the accuracy is very low. It detects everyone as male or female. For single person, the accuracy is great

**Comment by oarriaga** [comment]
Ok so your original question is resolved and I will close this issue.
I will answer your second question here but if you have further questions please submit another issue since it might help others who have the same problem.

On your second question,  I believe that what is happening is due to the `gender_offsets` hyper-parameter. This variable makes the box size bigger for prediction. The current values chosen for this variable are those that worked for the video demo. However, when the faces are located farther away, the offsets are not suitable for the prediction.  This variable should be dynamic and should depend on the current size of the bounding box I just have not find the time to come around with the proper fix. If you come up with something I would gladly accept a PR :)

**Comment by Zumbalamambo** [comment]
Okay... Im trying to fix it as well.... it appears to be quite hard... Any temporary workaround?

**Comment by oarriaga** [comment]
If you have further questions please submit another issue.
